spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtsecurity
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  token:
    secret: jtwappdemo
    expired: 3600000